### ISSUE TITLE
NullPointerException in Message.getCounterpart

### ISSUE THREAD

**Issue by tpreclik** [multimob/ceb2txt#2]
I get multiple null pointer exceptions when decrypting my backup:

```
Exception in thread "main" java.lang.NullPointerException
	at org.jxmpp.jid.impl.JidCreate.from(JidCreate.java:177)
	at org.jxmpp.jid.impl.JidCreate.fromOrNull(JidCreate.java:220)
	at im.conversations.ceb2txt.entities.Message.getCounterpart(Message.java:124)
	at im.conversations.ceb2txt.Main.main(Main.java:199)
```

Sounds like #14 is related. The corresponding `counterpart` string in Message leading to the exceptions were in my case either null or `conversations@conference.siacs.eu/`. These were the corresponding messages generated in the output when catching the exception and setting `nick` to `NULLPOINTEREXCEPTION`:

```
./group/hidden@conference.jabber.de/2017-06-26.txt:23:23 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-26.txt:23:24 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-22.txt:08:15 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/hidden@conference.jabber.de/2017-06-18.txt:21:05 NULLPOINTEREXCEPTION -> [file received over P2P (Jingle)]
./group/conversations@conference.siacs.eu/2023-05-05.txt:03:26 NULLPOINTEREXCEPTION <- dam spammers
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:30 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:31 NULLPOINTEREXCEPTION <- 
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:31 NULLPOINTEREXCEPTION <- Www.google.com
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠                                          
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
./group/conversations@conference.siacs.eu/2021-05-23.txt:16:32 NULLPOINTEREXCEPTION <- 䕂住䬠
```

A proper fix should be proposed by a more knowledgeable person.

**Comment by tpreclik** [comment]
Sorry duplicate of https://github.com/iNPUTmice/ceb2txt/issues/20
